# Generated by Django 4.2.7 on 2023-11-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='iscompleted',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
